#! /usr/bin/bash

increment=10
#In the order of 'xrandr --verbose' listing
SCREENS=("HDMI-0" "DP-4")
#manually add more names if needed

readarray -t brights < brightness.txt


if [ "$1" = 'update' ]; then
    xrandr --verbose | grep -m 2 -i brightness | cut -f2 -d ' ' | sed "s/^0\.//" | sed "s/\./0/" > brightness.txt
    exit
elif [ "$1" = 'refresh' ]; then
    foo=$(printf %.2f "$((brights[0]))e-2") #" dirty hack for coloration bug
    xrandr --output "${SCREENS[0]}" --brightness "$foo"
    foo=$(printf %.2f "$((briSCREEN2))e-2")
    xrandr --output "${SCREENS[1]}" --brightness "$foo"
    #manually update here
    exit
elif [ "$1" = '+' ]; then
    for i in "${!brights[@]}"; do
        if [[ -z "$2" || "$2" =~ "${SCREENS[$i]}" ]]; then
            let brights[i]=brights[i]+increment
            #prevent out of range (yes we authorize 20% of 'bonus' brightness to support overexposing if wanted)
            if [[ "${brights[$i]}" -gt "120" ]]; then
                brights[i]="120"
            fi
            #back to a float
            foo=$(printf %.2f "$((brights[i]))e-2")
            xrandr --output "${SCREENS[$i]}" --brightness "$foo"
        fi
    done
elif [ "$1" = '-' ]; then
    #for each index of screen
    for i in "${!brights[@]}"; do
        if [[ -z "$2" || "$2" =~ "${SCREENS[$i]}" ]]; then
            let brights[i]=brights[i]-increment
            #prevent out of range
            if [[ "${brights[$i]}" -lt "0" ]]; then
                brights[i]="0"
            fi
            #back to a float
            foo=$(printf %.2f "$((brights[i]))e-2")
            xrandr --output "${SCREENS[$i]}" --brightness "$foo"
        fi
    done
fi

for i in "${!brights[@]}"; do
    echo "${brights[$i]}"
done > brightness.txt
